# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxydoctor" do
  version "0.5.0"

  on_macos do
    sha256 "b212a80245747b676b5e4453362ab37aac0e0b4b84d696442feffac0cb5a5de2"
    url "https://github.com/francomano/ProxyDoctor/releases/download/v#{version}/proxydoctor_#{version}_darwin_all.tar.gz",
        verified: "github.com/francomano/ProxyDoctor/"
  end

  on_linux do
    on_intel do
      sha256 "1edf28c6e9ff21a2ef0bd82698e88921d56424c054476be5abf25b5f59a81dbd"
      url "https://github.com/francomano/ProxyDoctor/releases/download/v#{version}/proxydoctor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/francomano/ProxyDoctor/"
    end
    on_arm do
      sha256 "497bc0a6d4c9288a5df11621daab3306a5ceabe9adfc7f6d66f5511b0de1ed3d"
      url "https://github.com/francomano/ProxyDoctor/releases/download/v#{version}/proxydoctor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/francomano/ProxyDoctor/"
    end
  end

  name "proxydoctor"
  desc "Comprehensive proxy diagnostics tool: test, compare and use HTTP/HTTPS/SOCKS4/SOCKS5 proxies"
  homepage "https://github.com/francomano/ProxyDoctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proxydoctor"

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed or notarized. If macOS blocks it, run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/proxydoctor"
  EOS
end
